Lofine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Lofine import settings
from User import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('User.urls', namespace='user')),
    path('friends/', include('friends.urls', namespace='friends')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('friendship/', include('friendship.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

handler404 = views.got_404

User/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView


app_name = 'User'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('profile/', views.UserProfile.as_view(), name='profile'),
    path('registration/', views.RegisterUser.as_view(), name='regist'),
    path('settings/', views.SettingsUser.as_view(), name='settings'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

friends/urls.py
from django.urls import path
from friends import views


app_name = 'friends'


urlpatterns = [
    path('friends-search/', views.SearchView.as_view(), name='search_friends'),
    path('friends-user/', views.friends_user, name='friends_user'),
    path('friends-people/<slug:tag_user>', views.OtherUserProfile.as_view(), name='user-click'),
    path('add_friend', views.add_friend, name='add_frind'),
    path('del_friend', views.del_friend, name='del_frind'),
]

User/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    title = models.TextField(max_length=50, blank=True, verbose_name='О пользователе')
    birthday = models.DateField(verbose_name='Дата рождения')
    photo = models.ImageField(upload_to="users/%Y/%m/%d/", blank=True, null=True, verbose_name='Фото')
    country = models.CharField(max_length=60, blank=True, verbose_name='Страна')
    city = models.CharField(max_length=85, blank=True, verbose_name='Город')
    tag_user = models.CharField(max_length=20, verbose_name='Тег', null=True)
    telephone_number = models.CharField(max_length=18, verbose_name='Номер телефона')
    

User/forms.py
import datetime

from typing import Any
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms.forms import ValidationError
from django.contrib.auth import authenticate


class UserAuthoriateForm(AuthenticationForm):
    def __init__(self, *args, **kwargs): # Применяем к полям формы свои стили
        super(UserAuthoriateForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'input'})
        self.fields['password'].widget.attrs.update({'class': 'input'})
    
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput()
                               )
    
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput())
        
    class Meta:
        model = get_user_model()


    def clean_username(self) -> dict[str, Any]:
        username = self.cleaned_data['username']
        self.username = username
        
        if get_user_model().objects.filter(username=username).exists():
            return username
        
        raise ValidationError('Пользователя с таким username не существует')

    def clean_password(self) -> dict[str, Any]:
        password = self.cleaned_data['password']
        
        if authenticate(username=self.username, password=password):
            return password
        
        raise ValidationError('Проверьте имя пользователя или пароль. Оба поля могут быть чувствительны к регистру')
    
    
class RegistrationUserForm(UserCreationForm):
    def __init__(self, *args, **kwargs): # Применяем к полям формы свои стили
        super(RegistrationUserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'input'})
        self.fields['password1'].widget.attrs.update({'class': 'input'})
        self.fields['password2'].widget.attrs.update({'class': 'input'})
        self.fields['first_name'].widget.attrs.update({'class': 'input'})
        self.fields['last_name'].widget.attrs.update({'class': 'input'})
        self.fields['email'].widget.attrs.update({'class': 'input'})
        self.fields['telephone_number'].widget.attrs.update({'class': 'input art-stranger'})
        self.fields['birthday'].widget.attrs.update({'class': 'input'})
        self.fields['tag_user'].widget.attrs.update({'class': 'input'})
        
 
    username = forms.CharField(label='Логин')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput())
    email = forms.EmailField(label='E-mail', max_length=256)
    this_year = datetime.date.today().year
    birthday = forms.DateField(widget=forms.SelectDateWidget(years=tuple(range(this_year - 100, this_year - 5))), label='День рождение')
    telephone_number = forms.CharField(max_length=20, label='Номер телефона')
    tag_user = forms.CharField(max_length=20, label='Тег')
    first_name = forms.CharField(label='Имя', max_length=30)
    last_name = forms.CharField(label='Фамилия', max_length=20)
    
    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'email', 'first_name', 'last_name', 'tag_user', 'telephone_number', 'birthday')
        
    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Такой E-mail уже существует')
        return email
    
    def clean_tag_user(self):
        user_tag = self.cleaned_data['tag_user']
        if get_user_model().objects.filter(tag_user=user_tag).exists():
            raise forms.ValidationError('Пользователь с таким тегом уже существует')
        return user_tag


class SettingFormUser(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин')
    email = forms.EmailField(disabled=True, label='E-mail')
    first_name = forms.CharField(label='Имя', required=False, max_length=30)
    last_name = forms.CharField(label='Фамилия', required=False, max_length=20)
    tag_user = forms.CharField(max_length=20, label='Тег', required=False)
    title = forms.CharField(max_length=50, label='Описание профиля', required=False)
    country = forms.CharField(max_length=60, label='Страна', required=False)
    city = forms.CharField(max_length=85, label='Город', required=False)
    
    
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name',
                  'last_name', 'photo', 'tag_user',
                  'title', 'country', 'city',
                  'telephone_number')
        
        
    def clean_tag_user(self):
        user_tag = self.cleaned_data['tag_user']
        user_1 = get_user_model().objects.filter(tag_user=user_tag)
        if user_1.exists() and self.cleaned_data['username'] != user_1[0].username:
            raise forms.ValidationError('Пользователь с таким тегом уже существует')
        
        return user_tag

User/views.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.contrib.auth.views import LoginView
from User.forms import UserAuthoriateForm, RegistrationUserForm, SettingFormUser
from django.views.generic import CreateView, DetailView, UpdateView, TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model


class HomePage(TemplateView):
    template_name = 'User/home.html'


class UserProfile(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = 'User/profile.html'
    context_object_name = 'post'
    
    def get_object(self, queryset=None):
        return self.request.user


class RegisterUser(CreateView):
    form_class = RegistrationUserForm
    template_name = 'User/register.html'
    success_url = reverse_lazy('User:login')


class LoginUser(LoginView):
    form_class = UserAuthoriateForm
    template_name = 'User/login.html'


class SettingsUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = "User/settings.html"
    form_class = SettingFormUser
    extra_context = {
        'title': 'Настройки'
    }
    
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Model:
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('user:profile')


def got_404(request, exception):
    return HttpResponse('<h1>Ошибка 404, Пользователь с таким тегом не найден</h1>')

User/templates/User/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'User/css/main.css' %}">
    <link href="https://necolas.github.io/normalize.css/8.0.1/normalize.css" rel="stylesheet">
    <title>Lofine</title>
</head>
<body class="gradient">
    <div class="flowtext">
        <h1>Lofine</h1>
    </div>

    <div class="choice">
        <button class="glow-on-hover" type="button">
            <a href='{% url "user:regist" %}'>Регистрация</a>
        </button>
        
        <button class="glow-on-hover" type="button">
            <a href='{% url "user:login" %}'>Вход</a>
        </button>
    </div>
</body>
</html>

User/templates/User/login.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={% static "User/css/style.css" %}>
    <link rel="stylesheet" href={% static "User/css/register_login.css" %}>
    <link href="https://necolas.github.io/normalize.css/8.0.1/normalize.css" rel="stylesheet">
    <title>Login</title>
</head>
<body class='gradient'>
    <div class="parent">
        <form class="form" action="" method="post">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>

            <div class="form-error">{{ form.non_field_errors }}</div>
            {% for f in form %}
            <p><label for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
            {% endfor %}

            <p><a href={% url "User:regist" %}>Еще не зарегестрированы?</a></p>
            <button class="btn" type="submit">Вход</button>
        </form>
    </div>
</body>
</html>

User/templates/User/profile.html
{% extends "base.html" %}
{% load static %}
{% load friendshiptags %}

{% block content %}
    <div class="main-panel">
        <div class="image">
            {% if post.photo %}
            <img src="{{ post.photo.url }}">
            {% else %}
            <img src="{{ default_photo }}">
            {% endif %}
        </div>
        <div class="with-user">

            <div class="name-person">
                <h2>{{ post.first_name }} {{ post.last_name }}</h2>
                <hr>
                <h3>Online</h3>
                <h4 class="open-modal">Подробнее</h4>
            </div>
            
        </div>
        {% if post.tag_user != request.user.tag_user %}
        {% friends_or_not request.user post.id as fr_an_nt %}
        <div class="choice">
            <iframe name="iframe1" style="position: absolute; left: -9999px;"></iframe>
            {% if fr_an_nt %}

            <form action="{% url "friends:del_frind" %}" method='POST' target='iframe1'>
                {% csrf_token %}
                <button class="glow-on-hover" type="sumbit" onclick='refreshPage()'>
                    Удалить из друзей
                </button>
            </form>

            {% else %}
            
            <form action="{% url "friends:add_frind" %}" method='POST' target='iframe1'>
                {% csrf_token %}
                <button class="glow-on-hover" type='sumbit' onclick='refreshPage()'> 
                    Добавить в друзья
                </button>
            </form>

            {% endif %}

            <button class="glow-on-hover" type="button">
                Пожаловаться
            </button>

            <button class="glow-on-hover" type="button">
                + REP
            </button>
        </div>
        {% endif %}
    </div>
    <div class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2>Информация о пользователе</h2>
            <p>Имя: {{ post.first_name }}</p>
            <p>Фамилия: {{ post.last_name }}</p>
            <p>О себе: {{ post.title|default:"Не указано" }}</p>
            <p>Страна: {{ post.country|default:"Не указана" }}</p>
            <p>Тег: {{ post.tag_user }}</p>
            <p>Город: {{ post.city|default:"Не указан" }}</p>
            <p>Друзья: {% friends_count request.user %} </p>
            <p>Дата рождения: {{ post.birthday }}</p>
            <p>E-mail: {{ post.email }}</p>
            <p>Номер телефона: {{ post.telephone_number }}</p>
        </div>
    </div>
    <script src="{% static "User/js/script.js" %}"></script>
    <script src="{% static "User/js/disb.js" %}"></script>
    <script src="{% static "User/js/reload.js" %}"></script>
    
{% endblock content %}

User/templates/User/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={% static "User/css/style.css" %}>
    <link rel="stylesheet" href={% static "User/css/register_login.css" %}>
      
    <title>Register</title>
</head>
<body class='gradient'>
    <div class="parent">
        <form class="form" action="" method="post">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>

            <div class="form-error">{{ form.non_field_errors }}</div>
            {% for f in form %}
            <p><label for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
            {% endfor %}
        
            <p><a href={% url "User:login" %}>Уже зарегестрированы?</a></p>
            <button class="btn" type="submit">Регистрация</button>
        </form>
    </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src={% static "User/js/maska-nomera.js" %} type="text/javascript" ></script>

      <script>
$('.art-stranger').mask('+7 (999) 999-99-99');

$.fn.setCursorPosition = function(pos) {
  if ($(this).get(0).setSelectionRange) {
    $(this).get(0).setSelectionRange(pos, pos);
  } else if ($(this).get(0).createTextRange) {
    var range = $(this).get(0).createTextRange();
    range.collapse(true);
    range.moveEnd('character', pos);
    range.moveStart('character', pos);
    range.select();
  }
};


$('input[type="text"]').click(function(){
    $(this).setCursorPosition(4);  // set position number
  });
</script>
</body>
</html>

User/templates/User/settings.html
{% extends "base.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" href={% static "User/css/settings.css" %}>
{% endblock style %}

{% block content %}
<div id="w">
    <h1>{{ title }}</h1>
    <form id="contactform" name="contact" method="POST" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}
        <div class="center">
            <input type="submit" id="submitbtn" name="submitbtn" tabindex="5" value="Сохранить" >
        </div>
    </form>
</div>
{% endblock content %}  