Lofine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Lofine import settings
from User import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('User.urls', namespace='user')),
    path('friends/', include('friends.urls', namespace='friends')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('friendship/', include('friendship.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

handler404 = views.got_404

User/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView


app_name = 'User'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('profile/', views.UserProfile.as_view(), name='profile'),
    path('registration/', views.RegisterUser.as_view(), name='regist'),
    path('settings/', views.SettingsUser.as_view(), name='settings'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

friends/urls.py
from django.urls import path
from friends import views


app_name = 'friends'


urlpatterns = [
    path('friends-search/', views.SearchView.as_view(), name='search_friends'),
    path('friends-user/', views.friends_user, name='friends_user'),
    path('friends-people/<slug:tag_user>', views.OtherUserProfile.as_view(), name='user-click'),
    path('add_friend', views.add_friend, name='add_frind'),
    path('del_friend', views.del_friend, name='del_frind'),
]

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "User/css/style.css" %}">
    {% block style %}{% endblock style %}
    <title>Lofine</title>
</head>
<body>
    <div class="sidenav">
        <a href="{% url 'user:profile' %}"><img src={% static "User/images/free-icon-home-button-6490332.png" %}></a>
        <a href="{% url 'user:settings' %}"><img src={% static "User/images/free-icon-settings-126472.png" %}></a>
        <a href="{% url 'friends:friends_user' %}"><img src={% static "friends/images/free-icon-people-6647733.png" %}></a>
		<a href="{% url 'friends:search_friends' %}"><img src={% static "friends/images/free-icon-search-magnifier-symbol-of-interface-51658.png" %}></a>
        <a href="{% url 'user:logout' %}"><img src={% static "User/images/free-icon-exit-402718.png" %}></a>
    </div>
    {% block content %}
    {% endblock content %}
</body>
</html>